### ISSUE TITLE
No play issue

### ISSUE THREAD

**Issue by rgerr** [mcfisto/homebridge-homepod-radio#14]
Hi there, this plug-in has some real potential. I got very excited the minute I saw it, but I have not been able to make it work just yet.

I installed it via sudo npm install -g —unsafe-perm Homebridge-AirTunes-radio (gave errors without unsafe-perm), then added the device in my config. I double checked the right ip for the HomePod and audio link, but when I activate the device in the Home app, no audio is being played. Also deleted the plug-in in full and reinstalled it.

I added the following to my config:

        {
            "accessory": "HomePodRadio",
            "name": "Radio Two",
            "streamUrl": "http://icecast.omroep.nl/radio2-bb-mp3",
            "host": "192.168.1.115",
            "volume": 15,
            "port": 5000
        },

homebridge log:

[7/12/2019, 5:17:03 PM] [Radio Two] Turning Radio Two on
Config2: {"accessory":"HomePodRadio","name":"Radio Two","streamUrl":"http://icecast.omroep.nl/radio2-bb-mp3","host":"192.168.1.115","volume":15,"port":5000}
Device: {"_events":{},"_eventsCount":1,"udpServers":{"_events":{},"_eventsCount":1,"status":1,"control":{"socket":{"_events":{},"_eventsCount":1,"type":"udp4","fd":null},"port":null,"name":"control"},"timing":{"socket":{"_events":{},"_eventsCount":1,"type":"udp4","fd":null},"port":null,"name":"timing"},"hosts":["192.168.1.115"]},"audioOut":{"_events":{},"_eventsCount":1,"lastSeq":0,"hasAirTunes":true},"type":"airtunes","host":"192.168.1.115","port":5000,"key":"192.168.1.115:5000","rtsp":{"_events":{},"_eventsCount":0,"audioOut":{"_events":{},"_eventsCount":1,"lastSeq":0,"hasAirTunes":true},"status":0,"socket":null,"cseq":0,"announceId":null,"activeRemote":418640421,"dacpId":"603f843ddad1aa93","session":null,"timeout":null,"volume":15,"password":null,"passwordTried":false,"requireEncryption":false,"trackInfo":null,"artwork":null,"artworkContentType":null,"callback":null,"controlPort":null,"timingPort":null,"heartBeat":null},"audioCallback":null,"encoder":{},"audioSocket":{"_events":{},"_eventsCount":0,"type":"udp4","fd":null}}
[7/12/2019, 5:17:09 PM] [Radio Two] Turning Radio Two off

**Comment by saury** [comment]
Maybe your streamUrl is not supported. Try other one. 
For example: `http://listen.181fm.com/181-highway_128k.mp3`

**Comment by rgerr** [comment]
Tried changing the url to the one hou suggested and restarted homebridge, but still nothing, unfortunatly.

**Comment by Luftloch80** [comment]
Have the same problem. Do you need to install any other Module?
AirTunes,
Which npm version which Node Version to use

**Comment by rgerr** [comment]
I am using node v10.16 and npm V6.10.1

**Comment by rgerr** [comment]
Also tried installing it on a Raspberry pi 3b, without any luck. Tried several streams, but nothing comes out of my HomePod.

**Comment by mszf** [comment]
I had some issues at the end got it work but only with very few streams. This is not a answer or solution for this plug-in but in coming version 13 of iOS  you can do this natively in HomeKit . I mean start a audio stream from a HomeKit automation or a scene.

**Comment by rgerr** [comment]
Do you have a screenshot or link for this? Have not heard about this anywhere.

**Comment by mszf** [comment]
![262D4266-1131-42E9-A869-2DA1A752C204](https://user-images.githubusercontent.com/25150520/61181523-31727c80-a628-11e9-8257-a3b037cc362f.jpeg)

This is not just for HomePods but generally for all AirPlay2 devices. Right now in iOS13 beta you need a newer  version of HomePod software to make it work (was working in beta 1) but it already works with Apple TV when running on tvOS beta. iOS13 makes it possible to use any AirPlay2 device in HomeKit scenes, automations and even in Shortcuts.

**Comment by mszf** [comment]
![BF2F4763-0050-4FE4-A433-94B6D94E4B41](https://user-images.githubusercontent.com/25150520/61181692-f1ac9480-a629-11e9-9f4f-8f528d26daa2.jpeg)
![B7915CBF-5574-40C2-A8FA-A1FCFBDA2482](https://user-images.githubusercontent.com/25150520/61181693-f1ac9480-a629-11e9-88d3-61812bd2111e.jpeg)

**Comment by rgerr** [comment]
That looks promising, can you play costum audio files or streams?

**Comment by mszf** [comment]
This is supposed to work with Apple Music with audio and video content and with radio stations. Apple will add in iOS13 support for radio stations from all over the world and you can also upload custom audio content to Apple Music. 
In Shortcuts you can already use also files stored in your iCloud account or some other 3rd parties cloud services but it is unclear if this part is also going to work in HomeKit

**Comment by rgerr** [comment]
Ah, so, to be clear, the iOS 13 update will replace this plug-in? And we will be able to add costum audio files via iTunes and have it played via automations in HomeKit on the HomePod?

**Comment by mszf** [comment]
That's correct. After uploading your custom audio files to Apple Music trough iTunes you will able to play them on HomePod via HomeKit automations or scenes.

**Comment by rgerr** [comment]
Thanks for sharing this, I’ll just be patient untill september then.
