### ISSUE TITLE
No playback controls with HomePod, Siri or control center

### ISSUE THREAD

**Issue by badrabbit** [mcfisto/homebridge-homepod-radio#2]
Thanks for sharing! Just installed 0.2.0 and it's working fine.

But right now, there is no way to start/stop playing the stream with the HomePod itself or via control center on iOS.
Tapping on top of the HomePod or saying "Hey Siri, stop!" has no effect. The stream keeps on playing unless i stop it in the home app.

Any chance to fix this?

**Comment by mcfisto** [comment]
Hey!
Thanks for feedback!

Sorry for troubles, I’ll need to clarify this in documentation. Problem is that playback is controlled by HomeBridge (more precisely my app), so HomePod has nothing to do with it. The radio stream is published as a switch, so you could control it as a switch:
“Hey Siri, turn on BlahBlah”
“Hey Siri, turn off BlahBlah”
where BlahBlah is name of accesory in your config.

Please let me know if this works.

I will also do my best to implement ability to control volume from HomeKit as now you could control it just from HomePod.

Regards,
Daniel.

**Comment by badrabbit** [comment]
Thanks! "Hey Siri, turn on/off [name of accessory]" works just fine.

**Comment by mcfisto** [comment]
Invalid.
