### ISSUE TITLE
mcfisto

### ISSUE THREAD

**Issue by SmartHank1** [mcfisto/homebridge-homepod-radio#5]
Hey mcfisto,
fantastic plugin, luckily we have people like you delivering what Apple doesn't want... ;-)
Unfortunately I cannot make it work, I installed the plugin and tried my own config.
The lightbulb shows up, after a few seconds it switches off. 
Here is the outcome of the home bridge log... Please note: I erased the IP

`Jan 26 16:32:52 hbridge3 homebridge[2212]: [2019-1-26 16:32:52] [Radio Two] Turning Radio Two on
Jan 26 16:32:52 hbridge3 homebridge[2212]: Config2: {"accessory":"HomePodRadio","name":"Radio Two","streamUrl":"http://icecast6.play.cz/cro2-128.mp3","host":"XXX.XXX.X.XX","volume":15,"port":5000}
Jan 26 16:32:52 hbridge3 homebridge[2212]: Device: [Circular]`

I also tried to run it with exactly your config after I received some feedback that it might be due to a stream that doesn't fit at all... Unfortunately the same outcome...

Would be great if you might be able to help.
Do I need to change something with the port?

THX

**Comment by Quest1984** [comment]
Got the same issue, but I don't have HomePod, I tried to use plugin with Airport Express.

**Comment by SmartHank1** [comment]
Problem solved. Was not due to the Plugin but the Settings for the HomePod. Needed to give access to all people in the network and not to ‚homerelated‘ people...
